version: "3.7"

services:
  plexms:
    container_name: plexms
    restart: unless-stopped
    image: plexinc/pms-docker
    devices:
      - /dev/dri:/dev/dri # For Intel QSV HW Transcoding
    privileged: true
    volumes:
      - ${PLEX_DIR}/plexms:/config
      - ${MEDIA_DATA}/transcode:/transcode
      - ${MEDIA_DATA}:/media
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
    networks:
      - default
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.entrypoints=web
      - traefik.http.routers.plex-sec.entrypoints=websecure
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.routers.plex-sec.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.services.plex-sec.loadbalancer.server.port=32400
      - traefik.http.middlewares.tls-redirect.redirectscheme.scheme=https
      - traefik.http.routers.plex.middlewares=tls-redirect
      - traefik.http.routers.plex-sec.tls=true
      - traefik.http.routers.plex-sec.tls.certresolver=cfdns

  tautulli:
    container_name: tautulli
    restart: unless-stopped
    image: linuxserver/tautulli
    depends_on:
      - plexms
    ports:
      - 32500:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PLEX_DIR}/tautulli:/config
    networks:
      - default
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.entrypoints=web
      - traefik.http.routers.tautulli-sec.entrypoints=websecure
      - traefik.http.routers.tautulli.rule=Host(`stats.${DOMAIN}`)
      - traefik.http.routers.tautulli-sec.rule=Host(`stats.${DOMAIN}`)
      - traefik.http.services.tautulli-sec.loadbalancer.server.port=8181
      - traefik.http.middlewares.tls-redirect.redirectscheme.scheme=https
      - traefik.http.routers.tautulli.middlewares=tls-redirect
      - traefik.http.routers.tautulli-sec.middlewares=hsts
      - traefik.http.routers.tautulli-sec.tls=true
      - traefik.http.routers.tautulli-sec.tls.certresolver=cfdns

networks:
  traefik-network:
    external: true
  default:
    driver: bridge