version: "3.7"

# Will Fantom

services:

  # Traefik | Secure reverse proxy
  traefik:
    container_name: traefik
    restart: always
    image: traefik:latest
    networks:
      - default
      - traefik-network
    ports:
      - 8080:8080
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BASE_DIR}/traefik:/etc/traefik
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.${DOMAIN}
      - traefik.port=8080
      - traefik.docker.network=traefik-network
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.SSLHost=example.com
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
      - traefik.frontend.auth.basic.users=${TRAEFIK_UNAME}:${TRAEFIK_PASS}

networks:
  traefik-network:
    external: true
  default:
    driver: bridge