version: "3.7"

# Will Fantom

services:

  # Node Exporter Prom
  prom-ne:
    container_name: prom-ne
    restart: always
    image: prom/node-exporter
    networks:
      - default
      - traefik-network
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  # Cadvisor
  cadvisor:
    container_name: cadvisor
    restart: always
    image: google/cadvisor
    networks:
      - default
      - traefik-network
    ports:
      - 9101:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  traefik-network:
    external: true
  default:
    driver: bridge